(function(){
  const Zip=self.SiteForgeZip;
  function ensure(project,files){
    if(!files['package.json'])files['package.json']=JSON.stringify({name:project.name||'siteforge-app',version:project.version||'1.0.0',private:true,scripts:{dev:'next dev',build:'next build',start:'next start'},dependencies:{next:'14.0.0',react:'18.2.0','react-dom':'18.2.0'},devDependencies:{tailwindcss:'^3.4.0',autoprefixer:'^10.4.0',postcss:'^8.4.0'}},null,2);
    if(!files['next.config.js'])files['next.config.js']="module.exports={};\n";
    if(!files['tailwind.config.cjs'])files['tailwind.config.cjs']="module.exports={content:['./app/**/*.{js,jsx,ts,tsx}','./pages/**/*.{js,jsx,ts,tsx}','./components/**/*.{js,jsx,ts,tsx}'],theme:{extend:{}},plugins:[]};\n";
    if(!files['postcss.config.cjs'])files['postcss.config.cjs']="module.exports={plugins:{tailwindcss:{},autoprefixer:{}}};\n";
    if(!files['app/globals.css'])files['app/globals.css']='@tailwind base;@tailwind components;@tailwind utilities;';
    const hasEntry=Object.keys(files).some(p=>/^app\/page\.(js|jsx|ts|tsx)$/.test(p)||/^pages\/index\.(js|jsx|ts|tsx)$/.test(p));
    if(!hasEntry)files['app/page.jsx']="import './globals.css';export default function Page(){return(<main className='min-h-screen flex items-center justify-center bg-slate-950 text-slate-50'><div className='max-w-xl mx-auto p-6 rounded-xl bg-slate-900 border border-slate-800'><h1 className='text-3xl font-bold mb-2'>SiteForge AI</h1><p className='text-slate-300 text-sm'>Generated from a website snapshot. Start customizing this page.</p></div></main>);}\n";
    if(!files['.eslintrc.json'])files['.eslintrc.json']=JSON.stringify({extends:['next','next/core-web-vitals']},null,2);
    if(!files['.prettierrc'])files['.prettierrc']=JSON.stringify({singleQuote:true,trailingComma:'none'},null,2);
    if(!files['README.md'])files['README.md']="# "+(project.name||'SiteForge Static Copy')+"\n\n## About\n\nThis is a static Next.js 14 export of a website, generated by **SiteForge**.\n\nThe project includes:\n- **Original HTML structure** from the scraped page\n- **Original CSS styling** (inline + external stylesheets)\n- **Downloaded assets** (images, backgrounds, etc.)\n- **Dark mode support** (if the original site had it)\n\n## Getting Started\n\n### Prerequisites\n- Node.js 18+ and npm\n\n### Installation\n\n```bash\nnpm install\n```\n\n### Development\n\n```bash\nnpm run dev\n```\n\nOpen [http://localhost:3000](http://localhost:3000) to view the site.\n\n### Production Build\n\n```bash\nnpm run build\nnpm run start\n```\n\n## Customization\n\nYou can customize the exported project:\n\n- **Styling**: Edit `public/legacy.css` to adjust the original styles\n- **Layout**: Edit `app/layout.jsx` to modify the page structure\n- **Add Components**: Create new React components in `app/` directory\n- **Tailwind CSS**: Customize `tailwind.config.cjs` for additional styling\n\n## Deployment\n\nDeploy to Vercel:\n\n```bash\nnpm install -g vercel\nvercel\n```\n\nOr deploy to any Next.js-compatible hosting (Netlify, AWS, etc.).\n\n## Notes\n\n- JavaScript from the original site is not included (for security and portability)\n- Interactive features that relied on JS will need to be re-implemented\n- Some external resources may not load if they have CORS restrictions\n\n---\n\nGenerated by [SiteForge](https://github.com/yourusername/siteforge)\n";
  }
  function dataUriToBytes(uri){const i=uri.indexOf(',');if(i===-1)return null;const b64=uri.slice(i+1);try{const bin=atob(b64),out=new Uint8Array(bin.length);for(let j=0;j<bin.length;j++)out[j]=bin.charCodeAt(j);return out;}catch(_){return null;}}
  async function buildProjectZip(project){
    const files={};
    if(Array.isArray(project.files))project.files.forEach(f=>{files[f.path]=f.content;});
    ensure(project,files);
    if(Array.isArray(project.assets))for(const a of project.assets){if(a.dataUri){const b=dataUriToBytes(a.dataUri);if(b)files[a.path]=b;}}
    return Zip.createZipBlobFromFiles(files);
  }
  function extractComponents(html){
    const components={};
    const patterns=[
      {name:'Header',selector:'header, [role="banner"], .header, .navbar, nav'},
      {name:'Footer',selector:'footer, [role="contentinfo"], .footer'},
      {name:'Card',selector:'.card, [class*="card"], article, .post'},
      {name:'Button',selector:'button, [role="button"], .btn'},
      {name:'Form',selector:'form, [role="form"]'},
      {name:'Modal',selector:'[role="dialog"], .modal, .popup'},
      {name:'Sidebar',selector:'aside, [role="complementary"], .sidebar'}
    ];
    
    const parser=typeof DOMParser!=='undefined'?new DOMParser():null;
    if(!parser)return components;
    
    try{
      const doc=parser.parseFromString(html,'text/html');
      for(const p of patterns){
        const els=doc.querySelectorAll(p.selector);
        if(els.length>0){
          const el=els[0];
          const code=el.outerHTML.slice(0,500);
          components[p.name]={
            count:els.length,
            sample:code,
            selector:p.selector
          };
        }
      }
    }catch(_){}
    return components;
  }
  
  async function buildStaticCopyZip(snapshot){
    const name=(snapshot&&snapshot.title)||'siteforge-static-copy';
    const project={name,version:'1.0.0',packageManager:'npm',files:[],assets:[]};
    const files={};
    const urlMap=(snapshot&&snapshot.assetUrlMap)||{};

    const fullHtml=String((snapshot&&snapshot.fullHtml)||'');
    let bodyHtml=fullHtml;
    let bodyClass='';
    const bodyMatch=fullHtml.match(/<body([^>]*)>([\s\S]*?)<\/body>/i);
    if(bodyMatch){
      const attrs=bodyMatch[1]||'';
      const inner=bodyMatch[2]||'';
      bodyHtml=inner;
      const classMatch=attrs.match(/class=["']([^"']*)["']/i);
      if(classMatch)bodyClass=classMatch[1];
    }
    bodyHtml=bodyHtml.replace(/<script[\s\S]*?<\/script>/gi,'');
    bodyHtml=bodyHtml.replace(/on\w+\s*=\s*["'][^"']*["']/gi,'');
    for(const[origUrl,newPath]of Object.entries(urlMap)){
      const regex=new RegExp(origUrl.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g');
      bodyHtml=bodyHtml.replace(regex,'/'+newPath);
    }
    const escapedBody=bodyHtml.replace(/`/g,'\\`');
    const escapedBodyClass=(bodyClass||'').replace(/"/g,'\\"');

    // Page component is empty; all markup is injected at layout level.
    files['app/page.jsx']="import './globals.css';\nexport default function Page(){ return null; }\n";

    // Minimal globals: just Tailwind and container helper.
    const globalsParts=[];
    globalsParts.push('@tailwind base;','@tailwind components;','@tailwind utilities;','');
    globalsParts.push('.siteforge-original { min-height: 100vh; }');
    files['app/globals.css']=globalsParts.join('\n');

    // Full scraped CSS goes into a static file that is linked from layout.
    const legacyParts=[];
    const inline=(snapshot&&snapshot.inlineStyles)||'';
    if(inline){
      legacyParts.push('/* Inline styles from source page */');
      let cssText=inline.replace(/<[^>]*>/g,'').replace(/<!--[\s\S]*?-->/g,'');
      for(const[origUrl,newPath]of Object.entries(urlMap)){
        const safe=origUrl.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
        const regex=new RegExp('url\\(["\']?'+safe+'["\']?\\)','g');
        cssText=cssText.replace(regex,'url(/'+newPath+')');
      }
      legacyParts.push(cssText);
    }
    const external=(snapshot&&snapshot.externalStyles)||{};
    Object.keys(external).forEach(nameKey=>{
      const css=external[nameKey];
      if(css){
        legacyParts.push('/* '+nameKey+' */');
        let cssText=css.replace(/<[^>]*>/g,'').replace(/<!--[\s\S]*?-->/g,'');
        for(const[origUrl,newPath]of Object.entries(urlMap)){
          const safe=origUrl.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
          const regex=new RegExp('url\\(["\']?'+safe+'["\']?\\)','g');
          cssText=cssText.replace(regex,'url(/'+newPath+')');
        }
        legacyParts.push(cssText);
      }
    });
    if(legacyParts.length)files['public/legacy.css']=legacyParts.join('\n');

    // Root layout with SEO metadata.
    const metaTags=(snapshot&&snapshot.meta)||{};
    const description=metaTags['description']||metaTags['og:description']||'A website exported by SiteForge.';
    const ogImage=metaTags['og:image']||'';
    
    files['app/layout.jsx']="import './globals.css';\n"+
      "export const metadata={\n"+
      "  title: \""+(name||'SiteForge Static Copy').replace(/"/g,'\\"')+"\",\n"+
      "  description: \""+(description||'').replace(/"/g,'\\"').slice(0,160)+"\",\n"+
      "  openGraph: {\n"+
      "    title: \""+(name||'SiteForge Static Copy').replace(/"/g,'\\"')+"\",\n"+
      "    description: \""+(description||'').replace(/"/g,'\\"').slice(0,160)+"\",\n"+
      "    type: 'website',\n"+
      "    url: '/',\n"+
      (ogImage ? "    image: '"+ogImage.replace(/"/g,'\\"')+"',\n" : "")+
      "  },\n"+
      "  robots: 'index, follow',\n"+
      "};\n"+
      "export default function RootLayout({children}){\n"+
      "  return (\n"+
      "    <html lang=\"fr\">\n"+
      "      <head>\n"+
      "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"+
      "        <meta name=\"theme-color\" content=\"#ffffff\" />\n"+
      "        <link rel=\"icon\" href=\"/favicon.ico\" />\n"+
      "        <link rel=\"stylesheet\" href=\"/legacy.css\" />\n"+
      "      </head>\n"+
      "      <body className=\""+escapedBodyClass+"\" dangerouslySetInnerHTML={{__html: `"+escapedBody+"`}} />\n"+
      "    </html>\n"+
      "  );\n"+
      "}\n";
    
    // Generate sitemap.xml
    files['public/sitemap.xml']='<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n'+
      '<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n'+
      '  <url>\n'+
      '    <loc>https://yourdomain.com/</loc>\n'+
      '    <lastmod>'+new Date().toISOString().split('T')[0]+'</lastmod>\n'+
      '    <changefreq>weekly</changefreq>\n'+
      '    <priority>1.0</priority>\n'+
      '  </url>\n'+
      '</urlset>\n';
    
    // Generate robots.txt
    files['public/robots.txt']='User-agent: *\n'+
      'Allow: /\n'+
      'Sitemap: https://yourdomain.com/sitemap.xml\n';
    
    // Extract and document components
    const components=extractComponents(fullHtml);
    const componentsDocs='# Component Guide\n\n'+
      'This page was analyzed and the following reusable components were detected:\n\n'+
      Object.entries(components).map(([name,info])=>
        '## '+name+'\n\n'+
        '- **Found**: '+info.count+' instance(s)\n'+
        '- **Selector**: `'+info.selector+'`\n'+
        '- **Sample HTML**:\n```html\n'+info.sample+'\n```\n'
      ).join('\n')+
      '\n## How to Use\n\n'+
      'You can extract these patterns into reusable React components in `app/components/`:\n\n'+
      '```jsx\n'+
      '// app/components/Header.jsx\n'+
      'export default function Header() {\n'+
      '  return (\n'+
      '    <header>\n'+
      '      {/* Your header content here */}\n'+
      '    </header>\n'+
      '  );\n'+
      '}\n'+
      '```\n';
    files['COMPONENTS.md']=componentsDocs;
    
    const assetMap=(snapshot&&snapshot.assets)||{};
    const assets=[];
    Object.keys(assetMap).forEach(fileName=>{
      const uri=assetMap[fileName];
      if(typeof uri==='string'&&uri.startsWith('data:')){
        assets.push({path:'public/'+fileName,dataUri:uri});
      }
    });
    project.assets=assets;

    Object.keys(files).forEach(p=>{project.files.push({path:p,content:files[p]});});
    const blob=await buildProjectZip(project);
    return{blob,project};
  }
  self.SiteForgeBuilder={buildProjectZip,buildStaticCopyZip};
})();
