(function(){
  function buildWordPressTheme(snapshot){
    const files={};
    const name=(snapshot&&snapshot.title)||'siteforge-wp-theme';
    const themeName=name.replace(/[^a-z0-9-]/gi,'-').toLowerCase();
    
    // Extract original <body> HTML from the scraped page
    const fullHtml=String((snapshot&&snapshot.fullHtml)||'');
    let bodyHtml=fullHtml;
    const bodyMatch=fullHtml.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
    if(bodyMatch)bodyHtml=bodyMatch[1];
    // Strip scripts and inline event handlers for safety
    bodyHtml=bodyHtml.replace(/<script[\s\S]*?<\/script>/gi,'');
    bodyHtml=bodyHtml.replace(/on\w+\s*=\s*["'][^"']*["']/gi,'');
    // Escape template literal backticks and ${ } sequences
    const escapedBody=bodyHtml.replace(/`/g,'\\`').replace(/\$\{/g,'\\${');
    
    // theme.json - WordPress block theme config
    files['theme.json']=JSON.stringify({
      "$schema":"https://schemas.wp.org/wp/6.0/theme.json",
      "version":2,
      "settings":{
        "appearanceTools":true,
        "color":{
          "palette":[
            {"color":"#000000","name":"Black","slug":"black"},
            {"color":"#ffffff","name":"White","slug":"white"},
            {"color":"#0066cc","name":"Blue","slug":"blue"},
            {"color":"#333333","name":"Dark Gray","slug":"dark-gray"}
          ]
        },
        "typography":{
          "fontSizes":[
            {"size":"14px","name":"Small","slug":"small"},
            {"size":"16px","name":"Base","slug":"base"},
            {"size":"20px","name":"Medium","slug":"medium"},
            {"size":"32px","name":"Large","slug":"large"}
          ]
        },
        "spacing":{
          "units":["px","%","em","rem","vw","vh"]
        }
      },
      "styles":{
        "color":{"background":"#ffffff","text":"#000000"},
        "typography":{"fontFamily":"Arial, sans-serif","fontSize":"16px"}
      }
    },null,2);
    
    // functions.php
    files['functions.php']=`<?php
/**
 * ${themeName} Theme Functions
 * Generated by SiteForge
 */

// Add theme support
add_theme_support('title-tag');
add_theme_support('post-thumbnails');
add_theme_support('responsive-embeds');
add_theme_support('wp-block-styles');

// Enqueue styles
function ${themeName.replace(/-/g,'_')}_enqueue_styles(){
  wp_enqueue_style('${themeName}-style',get_stylesheet_uri());
  wp_enqueue_style('${themeName}-legacy',get_template_directory_uri().'/legacy.css');
}
add_action('wp_enqueue_scripts','${themeName.replace(/-/g,'_')}_enqueue_styles');

// Register menus
register_nav_menus(array(
  'primary'=>__('Primary Menu','${themeName}'),
  'footer'=>__('Footer Menu','${themeName}')
));

// Custom logo support
add_theme_support('custom-logo',array(
  'height'=>100,
  'width'=>300,
  'flex-height'=>true,
  'flex-width'=>true
));
?>`;
    
    // style.css - Theme header (required for WordPress to recognize theme)
    files['style.css']=`/*
Theme Name: ${name}
Theme URI: https://siteforge.dev
Description: Website exported by SiteForge - A deterministic website cloning tool
Version: 1.0.0
Author: SiteForge
Author URI: https://siteforge.dev
License: GPL v2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${themeName}
Domain Path: /languages
Requires at least: 5.9
Tested up to: 6.4
Requires PHP: 7.4
*/

/* Theme styles */
html, body {
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  font-size: 16px;
  line-height: 1.6;
  color: #333;
}

a {
  color: #0066cc;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

/* Theme styles will be loaded from legacy.css */
@import url('./legacy.css');
`;
    
    // index.php - Main template
    files['index.php']=`<?php
/**
 * Main template file
 */
get_header();
?>
<main id="main" class="site-main">
  <?php
  if(have_posts()){
    while(have_posts()){
      the_post();
      ?>
      <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
        <header class="entry-header">
          <?php the_title('<h1 class="entry-title">','</h1>'); ?>
        </header>
        <div class="entry-content">
          <?php the_content(); ?>
        </div>
      </article>
      <?php
    }
    the_posts_pagination();
  }else{
    echo '<p>No posts found</p>';
  }
  ?>
</main>
<?php
get_footer();
?>`;
    
    // header.php
    files['header.php']=`<?php
/**
 * Header template
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
  <?php wp_body_open(); ?>
  <header id="masthead" class="site-header">
    <div class="site-branding">
      <?php
      if(has_custom_logo()){
        the_custom_logo();
      }
      ?>
      <div class="site-title-wrapper">
        <?php bloginfo('name'); ?>
      </div>
    </div>
    <nav id="site-navigation" class="main-navigation">
      <?php
      wp_nav_menu(array(
        'theme_location'=>'primary',
        'fallback_cb'=>'wp_page_menu'
      ));
      ?>
    </nav>
  </header>`;
    
    // footer.php
    files['footer.php']=`<?php
/**
 * Footer template
 */
?>
  <footer id="colophon" class="site-footer">
    <div class="site-info">
      <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?></p>
    </div>
    <?php
    wp_nav_menu(array(
      'theme_location'=>'footer',
      'fallback_cb'=>false
    ));
    ?>
  </footer>
  <?php wp_footer(); ?>
</body>
</html>`;
    
    // single.php - Single post template
    files['single.php']=`<?php
get_header();
?>
<main id="main" class="site-main">
  <?php
  while(have_posts()){
    the_post();
    ?>
    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
      <header class="entry-header">
        <?php the_title('<h1 class="entry-title">','</h1>'); ?>
        <div class="entry-meta">
          Posted on <?php echo get_the_date(); ?> by <?php the_author(); ?>
        </div>
      </header>
      <div class="entry-content">
        <?php the_content(); ?>
      </div>
    </article>
    <?php
  }
  ?>
</main>
<?php
get_footer();
?>`;
    
    // page.php - Page template
    files['page.php']=`<?php
get_header();
?>
<main id="main" class="site-main">
  <?php
  while(have_posts()){
    the_post();
    ?>
    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
      <header class="entry-header">
        <?php the_title('<h1 class="entry-title">','</h1>'); ?>
      </header>
      <div class="entry-content">
        <?php the_content(); ?>
      </div>
    </article>
    <?php
  }
  ?>
</main>
<?php
get_footer();
?>`;

    // front-page.php - Static front page using scraped HTML
    files['front-page.php']=`<?php
/**
 * Front page template generated by SiteForge
 */
get_header();
?>
<main id="siteforge-front">
${escapedBody}
</main>
<?php
get_footer();
?>`;
    
    // legacy.css - Scraped styles
    const legacyParts=[];
    const inline=(snapshot&&snapshot.inlineStyles)||'';
    if(inline){
      legacyParts.push('/* Inline styles from source page */');
      let cssText=inline.replace(/<[^>]*>/g,'').replace(/<!--[\s\S]*?-->/g,'');
      legacyParts.push(cssText);
    }
    const external=(snapshot&&snapshot.externalStyles)||{};
    Object.keys(external).forEach(nameKey=>{
      const css=external[nameKey];
      if(css){
        legacyParts.push('/* '+nameKey+' */');
        let cssText=css.replace(/<[^>]*>/g,'').replace(/<!--[\s\S]*?-->/g,'');
        legacyParts.push(cssText);
      }
    });
    if(legacyParts.length)files['legacy.css']=legacyParts.join('\n');
    
    // .gitignore
    files['.gitignore']='*.log\n.DS_Store\nnode_modules/\n.env\n.env.local\n';
    
    // README
    files['README.md']=`# ${name} - WordPress Theme\n\n`+
      `Generated by SiteForge from a website snapshot.\n\n`+
      `## Installation\n\n`+
      `1. Download and extract this theme folder\n`+
      `2. Upload to your WordPress site:\n`+
      `   - Via FTP: Upload to \`wp-content/themes/\`\n`+
      `   - Via WordPress Admin: Appearance > Themes > Upload Theme\n`+
      `3. Go to WordPress Admin > Appearance > Themes\n`+
      `4. Find this theme and click "Activate"\n\n`+
      `## Features\n\n`+
      `- Fully responsive design\n`+
      `- Block theme support (WordPress 5.9+)\n`+
      `- Custom logo support\n`+
      `- Navigation menu support\n`+
      `- Featured image support\n`+
      `- Dark mode CSS (if original site had it)\n\n`+
      `## Customization\n\n`+
      `- **Styles**: Edit \`legacy.css\` to modify styles\n`+
      `- **Functionality**: Edit \`functions.php\` to add features\n`+
      `- **Layout**: Edit template files (\`index.php\`, \`single.php\`, etc.)\n`+
      `- **Colors/Typography**: Edit \`theme.json\` for block editor settings\n\n`+
      `## File Structure\n\n`+
      `\`\`\`\n`+
      `theme/\n`+
      `├── theme.json          # Block theme configuration\n`+
      `├── functions.php       # Theme functions & hooks\n`+
      `├── style.css           # Theme header & base styles\n`+
      `├── index.php           # Main template\n`+
      `├── header.php          # Header template\n`+
      `├── footer.php          # Footer template\n`+
      `├── single.php          # Single post template\n`+
      `├── page.php            # Page template\n`+
      `├── legacy.css          # Scraped styles from original site\n`+
      `└── README.md           # This file\n`+
      `\`\`\`\n\n`+
      `## Support\n\n`+
      `For issues or questions, visit https://siteforge.dev\n`+
      `\n`+
      `---\n`+
      `Generated by [SiteForge](https://siteforge.dev) - Website Cloning Tool\n`;
    
    return files;
  }
  
  self.SiteForgeWordPressTheme={buildWordPressTheme};
})();
